server:
  port: 1023
spring:
  application:
    name: 'demo'
  datasource:
    url: 'jdbc:mysql://localhost:3306/demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetime'
    username: 'root'
    password: 'root'

# OAuth2 Config
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_OAUTH_CLIENT_ID}
            client-secret: ${FACEBOOK_OAUTH_CLIENT_SECRET}
